### ISSUE TITLE
Error:can't extract tailnet name from hostname

### ISSUE THREAD

**Issue by lox** [kevin-hanselman/tailscale-forward-auth#26]
I'm getting the following error

> 2023/05/10 12:12:29 can't extract tailnet name from hostname "alexandra.taildb452.ts.net."

**Comment by kevin-hanselman** [comment]
I'm guessing the issue is related to this code growing stale compared to Tailscale's [nginx-auth.go](https://github.com/tailscale/tailscale/blob/main/cmd/nginx-auth/nginx-auth.go), in particular the code around parsing the tailnet. PRs always welcome 😉.

And, with all due respect, I encourage you to provide minimal, complete, and verifiable examples in your bug reports. [This is an excellent guide](https://matthewrocklin.com/minimal-bug-reports).

**Comment by lox** [comment]
Apologies @kevin-hanselman, I was unusually brief on detail with this one. I often send that link to folks that do the same thing I was guilty of here, it's an excellent one. 

I will indeed make a PR, I'm quite excited about using this project more!
